# Generated by Django 5.1.2 on 2024-10-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_likes'),
        ('notes', '0002_notes_user'),
    ]

    operations = [
    ]
